---
# Per environment values which override defaults in hmpps-official-visits-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: official-visits-ui-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://official-visits-ui-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components-dev.hmpps.service.justice.gov.uk"
    DPS_HOME_PAGE_URL: "https://digital-dev.prison.service.justice.gov.uk"
    PRISONER_PROFILE_URL: "https://prisoner-dev.digital.prison.service.justice.gov.uk"
    LOCATIONS_INSIDE_PRISON_API_URL: 'https://locations-inside-prison-api-dev.hmpps.service.justice.gov.uk'
    PRISONER_SEARCH_API_URL: 'https://prisoner-search-dev.prison.service.justice.gov.uk'
    OFFICIAL_VISITS_API_URL: 'https://official-visits-api-dev.hmpps.service.justice.gov.uk'
    PRISON_API_URL: 'https://prison-api-dev.prison.service.justice.gov.uk'
    PERSONAL_RELATIONSHIPS_API_URL: 'https://personal-relationships-api-dev.hmpps.service.justice.gov.uk'
    CONTACTS_HOME_PAGE_URL: 'https://contacts-dev.hmpps.service.justice.gov.uk'
    ACTIVITIES_API_URL: 'https://activities-api-dev.prison.service.justice.gov.uk'
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-alerts-api-non-prod
