---
# Per environment values which override defaults in hmpps-official-visits-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: official-visits-ui-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://official-visits-ui-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components-preprod.hmpps.service.justice.gov.uk"
    DPS_HOME_PAGE_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    PRISONER_PROFILE_URL: "https://prisoner-preprod.digital.prison.service.justice.gov.uk"
    LOCATIONS_INSIDE_PRISON_API_URL: 'https://locations-inside-prison-api-preprod.hmpps.service.justice.gov.uk'
    PRISONER_SEARCH_API_URL: 'https://prisoner-search-preprod.prison.service.justice.gov.uk'
    OFFICIAL_VISITS_API_URL: 'https://official-visits-api-preprod.hmpps.service.justice.gov.uk'
    PRISON_API_URL: 'https://prison-api-preprod.prison.service.justice.gov.uk'
    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-official-visits-non-prod
